// Code generated by gobind. DO NOT EDIT.

// Java class mobile.CryptoKeyPair is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class CryptoKeyPair implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	CryptoKeyPair(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public CryptoKeyPair() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native byte[] getPrivKey();
	public final native void setPrivKey(byte[] v);
	
	public final native byte[] getPubKey();
	public final native void setPubKey(byte[] v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof CryptoKeyPair)) {
		    return false;
		}
		CryptoKeyPair that = (CryptoKeyPair)o;
		byte[] thisPrivKey = getPrivKey();
		byte[] thatPrivKey = that.getPrivKey();
		if (thisPrivKey == null) {
			if (thatPrivKey != null) {
			    return false;
			}
		} else if (!thisPrivKey.equals(thatPrivKey)) {
		    return false;
		}
		byte[] thisPubKey = getPubKey();
		byte[] thatPubKey = that.getPubKey();
		if (thisPubKey == null) {
			if (thatPubKey != null) {
			    return false;
			}
		} else if (!thisPubKey.equals(thatPubKey)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getPrivKey(), getPubKey()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("CryptoKeyPair").append("{");
		b.append("PrivKey:").append(getPrivKey()).append(",");
		b.append("PubKey:").append(getPubKey()).append(",");
		return b.append("}").toString();
	}
}

