// Code generated by gobind. DO NOT EDIT.

// Java class mobile.DecodedDIDKey is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class DecodedDIDKey implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	DecodedDIDKey(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public DecodedDIDKey() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native byte[] getData();
	public final native void setData(byte[] v);
	
	public final native String getKeyType();
	public final native void setKeyType(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof DecodedDIDKey)) {
		    return false;
		}
		DecodedDIDKey that = (DecodedDIDKey)o;
		byte[] thisData = getData();
		byte[] thatData = that.getData();
		if (thisData == null) {
			if (thatData != null) {
			    return false;
			}
		} else if (!thisData.equals(thatData)) {
		    return false;
		}
		String thisKeyType = getKeyType();
		String thatKeyType = that.getKeyType();
		if (thisKeyType == null) {
			if (thatKeyType != null) {
			    return false;
			}
		} else if (!thisKeyType.equals(thatKeyType)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getData(), getKeyType()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("DecodedDIDKey").append("{");
		b.append("Data:").append(getData()).append(",");
		b.append("KeyType:").append(getKeyType()).append(",");
		return b.append("}").toString();
	}
}

