// Code generated by gobind. DO NOT EDIT.

// Java class mobile.DIDKeyWrapper is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class DIDKeyWrapper implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	DIDKeyWrapper(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public DIDKeyWrapper() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native byte[] getPrivateKey();
	public final native void setPrivateKey(byte[] v);
	
	public final native String getDIDKey();
	public final native void setDIDKey(String v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof DIDKeyWrapper)) {
		    return false;
		}
		DIDKeyWrapper that = (DIDKeyWrapper)o;
		byte[] thisPrivateKey = getPrivateKey();
		byte[] thatPrivateKey = that.getPrivateKey();
		if (thisPrivateKey == null) {
			if (thatPrivateKey != null) {
			    return false;
			}
		} else if (!thisPrivateKey.equals(thatPrivateKey)) {
		    return false;
		}
		String thisDIDKey = getDIDKey();
		String thatDIDKey = that.getDIDKey();
		if (thisDIDKey == null) {
			if (thatDIDKey != null) {
			    return false;
			}
		} else if (!thisDIDKey.equals(thatDIDKey)) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getPrivateKey(), getDIDKey()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("DIDKeyWrapper").append("{");
		b.append("PrivateKey:").append(getPrivateKey()).append(",");
		b.append("DIDKey:").append(getDIDKey()).append(",");
		return b.append("}").toString();
	}
}

