// Code generated by gobind. DO NOT EDIT.

// Java class mobile.ECDSAKeyPair is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class ECDSAKeyPair implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ECDSAKeyPair(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ECDSAKeyPair() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	public final native long getPubKeyX();
	public final native void setPubKeyX(long v);
	
	public final native long getPubKeyY();
	public final native void setPubKeyY(long v);
	
	public final native long getPrivKeyX();
	public final native void setPrivKeyX(long v);
	
	public final native long getPrivKeyY();
	public final native void setPrivKeyY(long v);
	
	public final native long getPrivKeyD();
	public final native void setPrivKeyD(long v);
	
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ECDSAKeyPair)) {
		    return false;
		}
		ECDSAKeyPair that = (ECDSAKeyPair)o;
		long thisPubKeyX = getPubKeyX();
		long thatPubKeyX = that.getPubKeyX();
		if (thisPubKeyX != thatPubKeyX) {
		    return false;
		}
		long thisPubKeyY = getPubKeyY();
		long thatPubKeyY = that.getPubKeyY();
		if (thisPubKeyY != thatPubKeyY) {
		    return false;
		}
		long thisPrivKeyX = getPrivKeyX();
		long thatPrivKeyX = that.getPrivKeyX();
		if (thisPrivKeyX != thatPrivKeyX) {
		    return false;
		}
		long thisPrivKeyY = getPrivKeyY();
		long thatPrivKeyY = that.getPrivKeyY();
		if (thisPrivKeyY != thatPrivKeyY) {
		    return false;
		}
		long thisPrivKeyD = getPrivKeyD();
		long thatPrivKeyD = that.getPrivKeyD();
		if (thisPrivKeyD != thatPrivKeyD) {
		    return false;
		}
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {getPubKeyX(), getPubKeyY(), getPrivKeyX(), getPrivKeyY(), getPrivKeyD()});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ECDSAKeyPair").append("{");
		b.append("PubKeyX:").append(getPubKeyX()).append(",");
		b.append("PubKeyY:").append(getPubKeyY()).append(",");
		b.append("PrivKeyX:").append(getPrivKeyX()).append(",");
		b.append("PrivKeyY:").append(getPrivKeyY()).append(",");
		b.append("PrivKeyD:").append(getPrivKeyD()).append(",");
		return b.append("}").toString();
	}
}

