// Code generated by gobind. DO NOT EDIT.

// Java class mobile.ServiceSetArray is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class ServiceSetArray implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	ServiceSetArray(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public ServiceSetArray() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field ServiceSetArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.Service
	
	// skipped method ServiceSetArray.Add with unsupported parameter or return types
	
	// skipped method ServiceSetArray.Get with unsupported parameter or return types
	
	public native long size();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof ServiceSetArray)) {
		    return false;
		}
		ServiceSetArray that = (ServiceSetArray)o;
		// skipped field ServiceSetArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.Service
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("ServiceSetArray").append("{");
		return b.append("}").toString();
	}
}

