// Code generated by gobind. DO NOT EDIT.

// Java class mobile.StringArray is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

/**
 * TODO solve this with generics
 */
public final class StringArray implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	StringArray(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public StringArray() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field StringArray.Items with unsupported type: []string
	
	// skipped method StringArray.Add with unsupported parameter or return types
	
	public native String get(long i);
	public native long size();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof StringArray)) {
		    return false;
		}
		StringArray that = (StringArray)o;
		// skipped field StringArray.Items with unsupported type: []string
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("StringArray").append("{");
		return b.append("}").toString();
	}
}

