// Code generated by gobind. DO NOT EDIT.

// Java class mobile.StringCollection is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public interface StringCollection {
	public StringCollection add(String s);
	public String get(long i);
	public long size();
	
}

