// Code generated by gobind. DO NOT EDIT.

// Java class mobile.VerificationMethodSetArray is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class VerificationMethodSetArray implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	VerificationMethodSetArray(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public VerificationMethodSetArray() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field VerificationMethodSetArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.VerificationMethodSet
	
	// skipped method VerificationMethodSetArray.Add with unsupported parameter or return types
	
	// skipped method VerificationMethodSetArray.Get with unsupported parameter or return types
	
	public native long size();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof VerificationMethodSetArray)) {
		    return false;
		}
		VerificationMethodSetArray that = (VerificationMethodSetArray)o;
		// skipped field VerificationMethodSetArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.VerificationMethodSet
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("VerificationMethodSetArray").append("{");
		return b.append("}").toString();
	}
}

