// Code generated by gobind. DO NOT EDIT.

// Java class mobile.VerificationMethodArray is a proxy for talking to a Go program.
//
//   autogenerated by gobind -lang=java github.com/TBD54566975/ssi-sdk-mobile/mobile
package mobile;

import go.Seq;

public final class VerificationMethodArray implements Seq.Proxy {
	static { Mobile.touch(); }
	
	private final int refnum;
	
	@Override public final int incRefnum() {
	      Seq.incGoRef(refnum, this);
	      return refnum;
	}
	
	VerificationMethodArray(int refnum) { this.refnum = refnum; Seq.trackGoRef(refnum, this); }
	
	public VerificationMethodArray() { this.refnum = __New(); Seq.trackGoRef(refnum, this); }
	
	private static native int __New();
	
	// skipped field VerificationMethodArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.VerificationMethod
	
	// skipped method VerificationMethodArray.Add with unsupported parameter or return types
	
	// skipped method VerificationMethodArray.Get with unsupported parameter or return types
	
	public native long size();
	@Override public boolean equals(Object o) {
		if (o == null || !(o instanceof VerificationMethodArray)) {
		    return false;
		}
		VerificationMethodArray that = (VerificationMethodArray)o;
		// skipped field VerificationMethodArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.VerificationMethod
		
		return true;
	}
	
	@Override public int hashCode() {
	    return java.util.Arrays.hashCode(new Object[] {});
	}
	
	@Override public String toString() {
		StringBuilder b = new StringBuilder();
		b.append("VerificationMethodArray").append("{");
		return b.append("}").toString();
	}
}

