
// Objective-C API for talking to the following Go packages
//
//	github.com/TBD54566975/ssi-sdk-mobile/tbdssi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tbdssi_FRAMEWORK_H__
#define __Tbdssi_FRAMEWORK_H__

#include "Tbdssi.objc.h"
#include "Universe.objc.h"

#endif
