
// Objective-C API for talking to the following Go packages
//
//	github.com/TBD54566975/ssi-sdk-mobile/src/ssi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ssi_FRAMEWORK_H__
#define __Ssi_FRAMEWORK_H__

#include "Ssi.objc.h"
#include "Universe.objc.h"

#endif
