// Objective-C API for talking to github.com/TBD54566975/ssi-sdk-mobile/identity Go package.
//   gobind -lang=objc github.com/TBD54566975/ssi-sdk-mobile/identity
//
// File is generated by gobind. Do not edit.

#ifndef __Identity_H__
#define __Identity_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class IdentityCryptoKeyPair;
@class IdentityDIDDocumentMobile;
@class IdentityDIDKeyWrapper;
@class IdentityDecodedDIDKey;
@class IdentityECDSAKeyPair;
@class IdentityRSAKeyPair;
@class IdentityServiceSetArray;
@class IdentityStringArray;
@class IdentityVerificationMethodArray;
@class IdentityVerificationMethodSetArray;
@protocol IdentityStringCollection;
@class IdentityStringCollection;

@protocol IdentityStringCollection <NSObject>
- (id<IdentityStringCollection> _Nullable)add:(NSString* _Nullable)s;
- (NSString* _Nonnull)get:(long)i;
- (long)size;
@end

@interface IdentityCryptoKeyPair : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable privKey;
@property (nonatomic) NSData* _Nullable pubKey;
@end

@interface IdentityDIDDocumentMobile : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) IdentityStringArray* _Nullable context;
@property (nonatomic) NSString* _Nonnull id_;
@property (nonatomic) NSString* _Nonnull controller;
@property (nonatomic) NSString* _Nonnull alsoKnownAs;
@property (nonatomic) IdentityVerificationMethodArray* _Nullable verificationMethod;
@property (nonatomic) IdentityVerificationMethodSetArray* _Nullable authentication;
@property (nonatomic) IdentityVerificationMethodSetArray* _Nullable assertionMethod;
@property (nonatomic) IdentityVerificationMethodSetArray* _Nullable keyAgreement;
@property (nonatomic) IdentityVerificationMethodSetArray* _Nullable capabilityInvocation;
@property (nonatomic) IdentityVerificationMethodSetArray* _Nullable capabilityDelegation;
@property (nonatomic) IdentityServiceSetArray* _Nullable services;
@end

@interface IdentityDIDKeyWrapper : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable privateJSONWebKey;
@property (nonatomic) NSString* _Nonnull didKey;
@end

@interface IdentityDecodedDIDKey : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable data;
@property (nonatomic) NSString* _Nonnull keyType;
@end

@interface IdentityECDSAKeyPair : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t pubKeyX;
@property (nonatomic) int64_t pubKeyY;
@property (nonatomic) int64_t privKeyX;
@property (nonatomic) int64_t privKeyY;
@property (nonatomic) int64_t privKeyD;
@end

@interface IdentityRSAKeyPair : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) int64_t pubKeyN;
@property (nonatomic) long pubKeyE;
@property (nonatomic) int64_t privKeyD;
// skipped field RSAKeyPair.Primes with unsupported type: []int64

@end

@interface IdentityServiceSetArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ServiceSetArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.Service

// skipped method ServiceSetArray.Add with unsupported parameter or return types

// skipped method ServiceSetArray.Get with unsupported parameter or return types

- (long)size;
@end

/**
 * TODO solve this with generics
 */
@interface IdentityStringArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field StringArray.Items with unsupported type: []string

// skipped method StringArray.Add with unsupported parameter or return types

- (NSString* _Nonnull)get:(long)i;
- (long)size;
@end

@interface IdentityVerificationMethodArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field VerificationMethodArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.VerificationMethod

// skipped method VerificationMethodArray.Add with unsupported parameter or return types

// skipped method VerificationMethodArray.Get with unsupported parameter or return types

- (long)size;
@end

@interface IdentityVerificationMethodSetArray : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field VerificationMethodSetArray.Items with unsupported type: []github.com/TBD54566975/ssi-sdk/did.VerificationMethodSet

// skipped method VerificationMethodSetArray.Add with unsupported parameter or return types

// skipped method VerificationMethodSetArray.Get with unsupported parameter or return types

- (long)size;
@end

/**
 * CreateDIDKey constructs a did:key from a specific key type and its corresponding public key
This method does not attempt to validate that the provided public key is of the specified key type.
A safer method is `GenerateDIDKey` which handles key generation based on the provided key type.
 */
FOUNDATION_EXPORT NSString* _Nonnull IdentityCreateDIDKey(NSString* _Nullable kt, NSData* _Nullable publicKey, NSError* _Nullable* _Nullable error);

/**
 * DecodeDIDKey Decode takes a did:key and returns the underlying public key value as bytes, the LD key type, and a possible error
 */
FOUNDATION_EXPORT IdentityDecodedDIDKey* _Nullable IdentityDecodeDIDKey(NSString* _Nullable d, NSError* _Nullable* _Nullable error);

/**
 * ExpandDIDKey Expand turns the DID key into a compliant DID Document
 */
FOUNDATION_EXPORT IdentityDIDDocumentMobile* _Nullable IdentityExpandDIDKey(NSString* _Nullable d, NSError* _Nullable* _Nullable error);

/**
 * GenerateDIDKey takes in a key type value that this library supports and constructs a conformant did:key identifier.
The function returns the associated private key value cast to the generic golang crypto.PrivateKey interface.
To use the private key, it is recommended to re-cast to the associated type. For example, called with the input
for a secp256k1 key:
privKey, didKey, err := GenerateDIDKey(Secp256k1)
if err != nil { ... }
// where secp is an import alias to the secp256k1 library we use "github.com/decred/dcrd/dcrec/secp256k1/v4"
secpPrivKey, ok := privKey.(secp.PrivateKey)
if !ok { ... }
 */
FOUNDATION_EXPORT IdentityDIDKeyWrapper* _Nullable IdentityGenerateDIDKey(NSString* _Nullable kt, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityCryptoKeyPair* _Nullable IdentityGenerateEd25519Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityECDSAKeyPair* _Nullable IdentityGenerateP224Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityECDSAKeyPair* _Nullable IdentityGenerateP256Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityECDSAKeyPair* _Nullable IdentityGenerateP384Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityECDSAKeyPair* _Nullable IdentityGenerateP521Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityRSAKeyPair* _Nullable IdentityGenerateRSA2048Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityECDSAKeyPair* _Nullable IdentityGenerateSecp256k1Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityCryptoKeyPair* _Nullable IdentityGenerateX25519Key(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT IdentityStringArray* _Nullable IdentityGetSupportedKeyTypes(void);

FOUNDATION_EXPORT IdentityStringArray* _Nullable IdentityGetSupportedSignatureAlgs(void);

FOUNDATION_EXPORT BOOL IdentityIsSupportedKeyType(NSString* _Nullable kt);

FOUNDATION_EXPORT BOOL IdentityIsSupportedSignatureAlg(NSString* _Nullable sa);

@class IdentityStringCollection;

@interface IdentityStringCollection : NSObject <goSeqRefInterface, IdentityStringCollection> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (id<IdentityStringCollection> _Nullable)add:(NSString* _Nullable)s;
- (NSString* _Nonnull)get:(long)i;
- (long)size;
@end

#endif
